In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
os.chdir(r"C:\Users\ghosa\Projects\ML\ass1\iris")

In [11]:
dataset = pd.read_csv("iris.data")
dataset.head()

s_length(cm)  s_width(cm)  p_length(cm)  p_width(cm)      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [12]:
dataset.groupby('species').size()

species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
dtype: int64

In [13]:
train, test = train_test_split(dataset, test_size = 0.4)

In [14]:
X_train = train[['s_length(cm)','s_width(cm)','p_length(cm)','p_width(cm)']]
y_train = train.species
X_test = test[['s_length(cm)','s_width(cm)','p_length(cm)','p_width(cm)']]
y_test = test.species

In [15]:
from sklearn.naive_bayes import GaussianNB

In [16]:
classifier = GaussianNB().fit(X_train,y_train)
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)

In [17]:
from sklearn.metrics import classification_report,confusion_matrix

In [21]:
print("Confusion Matrix:")
print(confusion_matrix(y_test,y_pred))

Confusion Matrix:
[[22  0  0]
 [ 0 22  1]
 [ 0  1 14]]


In [22]:
print(classification_report(y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        22
Iris-versicolor       0.96      0.96      0.96        23
 Iris-virginica       0.93      0.93      0.93        15

       accuracy                           0.97        60
      macro avg       0.96      0.96      0.96        60
   weighted avg       0.97      0.97      0.97        60

